language: generic 
services:
  - docker
cache:
  directories:
    - $HOME/.ccache
env:
  matrix:
    - ROS_DISTRO="foxy" BEFORE_SCRIPT='./scripts/ci_prebuild.sh' AFTER_SCRIPT='./scripts/ci_postbuild.sh'
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script: 
  - source .industrial_ci/travis.sh
