sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu CATKIN_CONFIG='--no-install' BEFORE_SCRIPT='./scripts/ci_prebuild.sh'
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - source .ci_config/travis.sh