sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    # Industrial CI first builds in install space with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    # Then the post build script runs the static analyzer and then runs the tests
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu BEFORE_SCRIPT='./scripts/ci_prebuild.sh' AFTER_SCRIPT='./scripts/ci_postbuild.sh'
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - source .ci_config/travis.sh