# Docker image base
image: ros:kinetic-ros-base

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir ~/catkin_ws
          - ln -s $BITBUCKET_CLONE_DIR ~/catkin_ws/src
          - cd ~/catkin_ws
          - apt-get update
          - apt-get install sudo clang-format-3.8 clang-3.8 lcov -y
          - rosdep update
          - rosdep install -y --from-paths src --ignore-src
          - source /opt/ros/*/setup.bash
          - cd  $BITBUCKET_CLONE_DIR
          - git ls-files | grep -E '\.[ch](pp)?$' | grep -v "thirdparty/" |  xargs clang-format-3.8 --style=file -i && git diff --exit-code || { git reset --hard; false; }
          - cd ~/catkin_ws
          # - scan-build-3.8 --status-bugs catkin_make -j1
          # - catkin_make -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          # - run-clang-tidy-3.8.py -clang-tidy-binary=clang-tidy-3.8 -p=build
          - ./src/coverage.sh
