controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    drive:
      type: diff_drive_controller/DiffDriveController
drive:
  ros__parameters:
    left_wheel_names: [front_left_wheel, rear_left_wheel]
    right_wheel_names: [front_right_wheel, rear_right_wheel]
    wheel_separation: 0.64
    wheel_radius: 0.15
    enable_odom_tf: false