controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    drive:
      type: ackermann_steering_controller/AckermannSteeringController
drive:
  ros__parameters:
    traction_joints_names: [rear_right_wheel, rear_left_wheel]
    steering_joints_names: [front_right_steer, front_left_steer]
    traction_track_width: 0.64
    steering_track_width: 0.64
    wheelbase: 1.04
    traction_wheels_radius: 0.19
    enable_odom_tf: false