name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  industrial_ci:
    name: ROS ${{ matrix.env.ROS_DISTRO }}
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main, DOCKER_IMAGE: 'osrf/ros:humble-desktop-full', AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true}
          # - {ROS_DISTRO: jazzy, ROS_REPO: main, AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true}
          # - {ROS_DISTRO: kilted, ROS_REPO: main, AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true, TARGET_CMAKE_ARGS: '-DCMAKE_COMPILE_WARNING_AS_ERROR=ON'}
          - {ROS_DISTRO: lyrical, ROS_REPO: main, DOCKER_IMAGE: 'osrf/ros:lyrical-desktop-full', AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true, TARGET_CMAKE_ARGS: '-DCMAKE_COMPILE_WARNING_AS_ERROR=ON'}
          - {ROS_DISTRO: rolling, ROS_REPO: main, OS_CODE_NAME: noble, DOCKER_IMAGE: 'osrf/ros:rolling-desktop-full-noble', AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true, TARGET_CMAKE_ARGS: '-DCMAKE_COMPILE_WARNING_AS_ERROR=ON'}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  coverage:
    name: Coverage (ROS Lyrical)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: lyrical
          ROS_REPO: main
          DOCKER_IMAGE: osrf/ros:lyrical-desktop-full
          CC: gcc
          CXX: g++
          ADDITIONAL_DEBS: gcovr
          TARGET_CMAKE_ARGS: '-DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_EXE_LINKER_FLAGS=--coverage -DCMAKE_SHARED_LINKER_FLAGS=--coverage'
          AFTER_SCRIPT: >-
            gcovr --root "$BASEDIR/${PREFIX}target_ws/src"
            --filter "$BASEDIR/${PREFIX}target_ws/src"
            --exclude '.*/test/.*'
            --print-summary "$BASEDIR/${PREFIX}target_ws/build"